// SentinelX PostgreSQL schema (docs/04_DATA_MODEL.md). Drizzle migrations are the only DDL source (D-010).
import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  doublePrecision,
  index,
  inet,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  smallint,
  text,
  timestamp,
  unique,
} from "drizzle-orm/pg-core";

// IDs are generated by the database so TypeScript and Python services share one rule (D-030).
const prefixedId = (prefix: string) =>
  text("id")
    .primaryKey()
    .default(sql.raw(`'${prefix}_' || substr(replace(gen_random_uuid()::text, '-', ''), 1, 16)`));

const createdAt = () => timestamp("created_at", { withTimezone: true }).notNull().defaultNow();
const score0to100 = (name: string, column: string) => check(name, sql.raw(`${column} BETWEEN 0 AND 100`));

export const severity = pgEnum("severity", ["LOW", "MEDIUM", "HIGH", "CRITICAL"]);
export const incidentStatus = pgEnum("incident_status", ["open", "investigating", "resolved"]);
export const runStatus = pgEnum("investigation_run_status", ["queued", "running", "completed", "failed"]);
export const actionOrigin = pgEnum("action_origin", ["llm", "fallback"]);
export const evidenceSourceType = pgEnum("evidence_source_type", [
  "event",
  "alert",
  "user_history",
  "ip_reputation",
  "related_logs",
  "mitre",
  "knowledge",
]);
export const reputationLevel = pgEnum("reputation_level", ["known_good", "unknown", "suspicious", "malicious"]);

// Console login accounts only; never joined with monitored identities (D-012).
export const analysts = pgTable("analysts", {
  id: prefixedId("an"),
  email: text("email").notNull().unique(),
  name: text("name").notNull(),
  passwordHash: text("password_hash").notNull(),
  createdAt: createdAt(),
});

export const securityEvents = pgTable(
  "security_events",
  {
    id: prefixedId("se"),
    externalEventId: text("external_event_id").notNull().unique(), // idempotency key (D-014)
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
    userId: text("user_id").notNull(), // monitored identity, no FK to analysts (D-012)
    sourceIp: inet("source_ip").notNull(),
    eventType: text("event_type").notNull(),
    action: text("action").notNull(),
    resource: text("resource").notNull(),
    status: text("status").notNull(),
    metadataJson: jsonb("metadata_json").notNull().default({}),
    createdAt: createdAt(),
  },
  (t) => [
    index("security_events_occurred_at_idx").on(t.occurredAt),
    index("security_events_user_time_idx").on(t.userId, t.occurredAt),
    index("security_events_ip_time_idx").on(t.sourceIp, t.occurredAt),
  ],
);

// Rule hits only (D-021).
export const detectionSignals = pgTable(
  "detection_signals",
  {
    id: prefixedId("sig"),
    eventId: text("event_id")
      .notNull()
      .references(() => securityEvents.id),
    ruleName: text("rule_name").notNull(),
    ruleScore: smallint("rule_score").notNull(),
    severity: severity("severity").notNull(),
    reason: text("reason").notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique("detection_signals_event_rule_uq").on(t.eventId, t.ruleName),
    score0to100("detection_signals_rule_score_ck", "rule_score"),
  ],
);

export const alerts = pgTable(
  "alerts",
  {
    id: prefixedId("alt"),
    eventId: text("event_id")
      .notNull()
      .unique()
      .references(() => securityEvents.id),
    riskScore: smallint("risk_score").notNull(),
    anomalyScore: doublePrecision("anomaly_score").notNull(),
    modelVersion: text("model_version").notNull(),
    severity: severity("severity").notNull(),
    reasonsJson: jsonb("reasons_json").notNull(),
    createdAt: createdAt(),
  },
  () => [score0to100("alerts_risk_score_ck", "risk_score")],
);

export const incidents = pgTable(
  "incidents",
  {
    id: prefixedId("inc"),
    title: text("title").notNull(),
    status: incidentStatus("status").notNull().default("open"),
    riskScore: smallint("risk_score").notNull(),
    severity: severity("severity").notNull(),
    primaryUserId: text("primary_user_id"),
    primaryIp: inet("primary_ip"),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    createdAt: createdAt(),
  },
  (t) => [
    index("incidents_status_updated_idx").on(t.status, t.updatedAt),
    score0to100("incidents_risk_score_ck", "risk_score"),
  ],
);

export const incidentEvents = pgTable(
  "incident_events",
  {
    incidentId: text("incident_id")
      .notNull()
      .references(() => incidents.id),
    eventId: text("event_id")
      .notNull()
      .references(() => securityEvents.id),
  },
  (t) => [primaryKey({ columns: [t.incidentId, t.eventId] }), index("incident_events_event_idx").on(t.eventId)],
);

export const incidentAlerts = pgTable(
  "incident_alerts",
  {
    incidentId: text("incident_id")
      .notNull()
      .references(() => incidents.id),
    alertId: text("alert_id")
      .notNull()
      .references(() => alerts.id),
  },
  (t) => [primaryKey({ columns: [t.incidentId, t.alertId] }), index("incident_alerts_alert_idx").on(t.alertId)],
);

// verdict_json holds only an accepted verdict; every model output is kept in raw_output_json (D-019).
export const investigationRuns = pgTable(
  "investigation_runs",
  {
    id: prefixedId("run"),
    incidentId: text("incident_id")
      .notNull()
      .references(() => incidents.id),
    status: runStatus("status").notNull().default("queued"),
    requiresReview: boolean("requires_review").notNull().default(false),
    verdictJson: jsonb("verdict_json"),
    rawOutputJson: jsonb("raw_output_json"),
    validationErrorsJson: jsonb("validation_errors_json"),
    modelName: text("model_name"),
    promptVersion: text("prompt_version"),
    errorMessage: text("error_message"),
    startedAt: timestamp("started_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [index("investigation_runs_incident_idx").on(t.incidentId)],
);

export const investigationTrace = pgTable(
  "investigation_trace",
  {
    id: prefixedId("trc"),
    investigationRunId: text("investigation_run_id")
      .notNull()
      .references(() => investigationRuns.id),
    stepIndex: integer("step_index").notNull(),
    actionType: text("action_type").notNull(),
    actionOrigin: actionOrigin("action_origin"), // null for system nodes such as load_incident
    toolName: text("tool_name"),
    inputJson: jsonb("input_json"),
    resultJson: jsonb("result_json"),
    evidenceIdsJson: jsonb("evidence_ids_json").notNull().default([]),
    retrievalRefsJson: jsonb("retrieval_refs_json").notNull().default([]),
    createdAt: createdAt(),
  },
  (t) => [
    unique("investigation_trace_run_step_uq").on(t.investigationRunId, t.stepIndex),
    check("investigation_trace_step_index_ck", sql`${t.stepIndex} >= 0`),
  ],
);

export const evidence = pgTable(
  "evidence",
  {
    id: prefixedId("ev"),
    investigationRunId: text("investigation_run_id")
      .notNull()
      .references(() => investigationRuns.id),
    sourceType: evidenceSourceType("source_type").notNull(),
    sourceId: text("source_id").notNull(),
    claim: text("claim").notNull(),
    dataJson: jsonb("data_json").notNull(),
    createdAt: createdAt(),
  },
  (t) => [index("evidence_run_idx").on(t.investigationRunId)],
);

export const knowledgeDocuments = pgTable(
  "knowledge_documents",
  {
    id: prefixedId("kd"),
    source: text("source").notNull(),
    externalId: text("external_id").notNull(),
    title: text("title").notNull(),
    contentHash: text("content_hash").notNull(),
    qdrantPointId: text("qdrant_point_id"),
    metadataJson: jsonb("metadata_json").notNull().default({}),
    createdAt: createdAt(),
  },
  (t) => [
    unique("knowledge_documents_source_external_uq").on(t.source, t.externalId),
    index("knowledge_documents_content_hash_idx").on(t.contentHash),
  ],
);

// Synthetic local reputation; score is 0 (benign) to 100 (malicious) (D-020).
export const ipReputation = pgTable(
  "ip_reputation",
  {
    ip: inet("ip").primaryKey(),
    reputation: reputationLevel("reputation").notNull(),
    score: smallint("score").notNull(),
    tagsJson: jsonb("tags_json").notNull().default([]),
    source: text("source").notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  () => [score0to100("ip_reputation_score_ck", "score")],
);

// Curated ATT&CK Enterprise subset (D-020).
export const mitreTechniques = pgTable(
  "mitre_techniques",
  {
    techniqueId: text("technique_id").primaryKey(),
    name: text("name").notNull(),
    tacticsJson: jsonb("tactics_json").notNull(),
    description: text("description").notNull(),
    attackVersion: text("attack_version").notNull(),
  },
  (t) => [check("mitre_techniques_id_ck", sql`${t.techniqueId} ~ '^T[0-9]{4}(\\.[0-9]{3})?$'`)],
);
